from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text
from datetime import datetime
from database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    second_name = Column(String, nullable=True)
    national_id = Column(String, unique=True, index=True, nullable=True)
    mobile = Column(String, unique=True, index=True, nullable=True)
    address = Column(String, nullable=True)
    role = Column(String, default="user")  # "user" | "admin" | "fixer"
    specialty = Column(String, nullable=True)  # for fixers: plumber, mason, painter, welder
    is_active = Column(Boolean, default=True)

class Message(Base):
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True) # the room owner
    sender_id = Column(Integer, ForeignKey("users.id"), nullable=True) # who sent the message; NULL for AI
    content = Column(String)
    is_ai = Column(Boolean, default=False) # True when the message was generated by the Gemini assistant
    timestamp = Column(DateTime, default=datetime.utcnow)

class Report(Base):
    """One defect report per successful /predict. Created at predict time (status
    'pending'); the reporter then fills location/severity/description via the
    metadata form, and the admin/fixer workflow drives status forward."""
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)  # the reporter
    image_path = Column(String)                       # original upload, relative to uploads/
    result_image_path = Column(String, nullable=True) # Grad-CAM annotated image
    result = Column(String)                            # e.g. "crack (0.87), rust (0.63)"
    primary_class = Column(String, nullable=True)      # top class -> drives fixer specialty suggestion
    num_detections = Column(Integer, default=0)
    location = Column(String, nullable=True, index=True)
    severity = Column(String, nullable=True)           # low | medium | high
    description = Column(Text, nullable=True)
    status = Column(String, default="pending", index=True)  # pending | assigned | fixer_done | completed
    assigned_fixer_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class DefectSpecialty(Base):
    """Maps a detected defect class to the fixer specialty that should handle it.
    Seeded at startup; editable later."""
    __tablename__ = "defect_specialties"

    id = Column(Integer, primary_key=True, index=True)
    defect_class = Column(String, unique=True, index=True)  # crack | water_damage | paint_peeling | rust
    specialty = Column(String)                              # mason | plumber | painter | welder

class CommunityPost(Base):
    __tablename__ = "community_posts"

    id = Column(Integer, primary_key=True, index=True)
    author_id = Column(Integer, ForeignKey("users.id"), index=True)
    content = Column(Text)
    image_path = Column(String, nullable=True)  # optional attached image, relative to uploads/
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

class CommunityComment(Base):
    """Flat reply to a post."""
    __tablename__ = "community_comments"

    id = Column(Integer, primary_key=True, index=True)
    post_id = Column(Integer, ForeignKey("community_posts.id"), index=True)
    author_id = Column(Integer, ForeignKey("users.id"))
    content = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

class CommunityReaction(Base):
    """An emoji reaction on either a post or a comment (exactly one target set)."""
    __tablename__ = "community_reactions"

    id = Column(Integer, primary_key=True, index=True)
    post_id = Column(Integer, ForeignKey("community_posts.id"), nullable=True, index=True)
    comment_id = Column(Integer, ForeignKey("community_comments.id"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True)
    emoji = Column(String)
